import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 다크 모드가 시스템 기본값을 따라가도록 설정 */}
      <ThemeProvider attribute="class" defaultTheme="system">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
